### ISSUE TITLE
`okta apps create` throws NPE when not logged in

### ISSUE THREAD

**Issue by mpaine-act** [okta/okta-cli#191]
I am trying 0.8 version build on Windows 10 and get the following error:

PS P:\> okta apps create
Application name [Movie-Explorer]:
Type of Application
(The Okta CLI only supports a subset of application types and properties):
> 1: Web
> 2: Single Page App
> 3: Native App (mobile)
> 4: Service (Machine-to-Machine)
Enter your choice [Web]: 3
java.lang.NullPointerException
        at java.net.URI$Parser.parse(URI.java:3104)
        at java.net.URI.<init>(URI.java:600)
        at java.net.URI.create(URI.java:881)
        at com.okta.cli.common.URIs.reverseDomain(URIs.java:27)
        at com.okta.cli.commands.apps.AppsCreate.createNativeApp(AppsCreate.java:128)
        at com.okta.cli.commands.apps.AppsCreate.runCommand(AppsCreate.java:88)
        at com.okta.cli.commands.BaseCommand.call(BaseCommand.java:41)
        at com.okta.cli.commands.BaseCommand.call(BaseCommand.java:26)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at com.okta.cli.OktaCli.run(OktaCli.java:64)
        at com.okta.cli.OktaCli.main(OktaCli.java:54)

PS P:\> java -version
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.7+10-LTS, mixed mode)

Is there something I did wrong?

**Comment by mpaine-act** [comment]
Thank you for your help.

**Comment by bdemers** [comment]
@mpaine-act I'll leave this open, we still want to fix it problem. Instead of an NPE, you should have received a message telling you to use `okta login` first.
