### ISSUE TITLE
Windows 10 'okta register' returns an error after entering verification code.

### ISSUE THREAD

**Issue by KostiantynDrozd-okta** [okta/okta-cli#57]
Windows 10 'okta register' returns an error after entering verification code.
No link to set password.

```
okta register
An existing Okta Organization (https://dev-6224545.okta.com) was found in C:\Users\User\.okta\okta.yaml
Overwrite configuration file? [Y/n]Y
Configuration file backed: C:\Users\User\.okta\okta.yaml.20201105T1539
First name: KOstya
Last name: Drozdov
Email address: testkostyadrozdov@gmail.com
Company: test
Creating new Okta Organization, this may take a minute:
OrgUrl: https://dev-9044671.okta.com
An email has been sent to you with a verification code.

Check your email
Verification code: 919053

An error occurred if you need more detail use the '--verbose' option

null
```

**Comment by bdemers** [comment]
@KostiantynDrozd-okta can you run that again with the `--verbose` command?

**Comment by KostiantynDrozd-okta** [comment]
@bdemers 

okta --verbose register
First name: KOstya
Last name: Drozdov
Email address: testkostyadrozdov@gmail.com
Company: test
Creating new Okta Organization, this may take a minute:
OrgUrl: https://dev-7766985.okta.com
An email has been sent to you with a verification code.

Check your email
Verification code: 636034
java.lang.UnsupportedOperationException
        at java.nio.file.Files.setPosixFilePermissions(Files.java:2078)
        at com.okta.cli.common.service.DefaultSdkConfigurationService.writeOktaYaml(DefaultSdkConfigurationService.java:92)
        at com.okta.cli.common.service.DefaultSetupService.verifyOktaOrg(DefaultSetupService.java:150)
        at com.okta.cli.commands.Register.call(Register.java:82)
        at com.okta.cli.commands.Register.call(Register.java:32)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at com.okta.cli.OktaCli.run(OktaCli.java:64)
        at com.okta.cli.OktaCli.main(OktaCli.java:54)

**Comment by KostiantynDrozd-okta** [comment]
Also commands `okta start` and `okta login` return null:

`C:\Users\User\Music>okta login --verbose
Okta Org URL: https://dev-6224545.okta.com
Enter your Okta API token, for more information see: https://bit.ly/get-okta-api-token
Okta API token: 001nOZ2vRLuEJP7C4SnrvDgzQhYpMJ-lqSOoAT69tk

An error occurred if you need more detail use the '--verbose' option

null`

`C:\Users\User\Music>okta login --verbose
Okta Org URL: https://dev-6224545.okta.com
Enter your Okta API token, for more information see: https://bit.ly/get-okta-api-token
Okta API token: 001nOZ2vRLuEJP7C4SnrvDgzQhYpMJ-lqSOoAT69tk

An error occurred if you need more detail use the '--verbose' option

null`

In case login, It returns null, but config file okta.yaml was created.
In case okta start, in returns null, and creates a folder with app name with only one .gitignore file.
